on: [push]

jobs:
  synchronous-analysis-with-blocking-result:
    name: SOOS SCA Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Run SOOS - Scan for vulnerabilities
      uses: soos-io/soos-sca-github-action@070148fd93ad76183d79aa793944ee3ec0646acd  #Get Latest Version from https://github.com/marketplace/actions/soos-core-sca
      with:
        project_name: "GitHub Actions - SCA v2.1.3"  
        client_id: ${{ secrets.SOOS_CLIENT_ID }}
        api_key: ${{ secrets.SOOS_API_KEY }}
        api_url: 'https://qa-api.soos.io/api/'
        log_level: "DEBUG"
        directories_to_exclude: 'manifests/java/**, manifests/PHP/**, invalid/**'
        files_to_exclude: 'manifests/node/npm/package.json, **/ruby/GEMFILE, invalid/package.json'
        branch_name: "test-branch" 
        output_format: SARIF 
        sca_version: 4.0.5-pre.1
